### PR TITLE
trying to fix upgrade

### PR DESCRIPTION
**Pull request by OniriCorpe**
## Problem

- #94 

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

### CODE REVIEW

**Comment by OniriCorpe** [comment]
!testme

**Comment by OniriCorpe** [comment]
same error :/

```text
Info : DEBUG - transforming...
Info : DEBUG - ✓ 121 modules transformed.
Info : DEBUG - "default" is not exported by "resources/js/vendor/webauthn/webauthn.js", imported by "resources/js/data/webauthn/loginWebAuthn.ts".
Info : DEBUG - file: /var/www/lychee/resources/js/data/webauthn/loginWebAuthn.ts:1:7
Info : DEBUG - 1: import WebAuthn from "@/vendor/webauthn/webauthn.js";
Info : DEBUG -           ^
Info : DEBUG - 2: import type { Alpine, AlpineComponent } from "alpinejs";
Info : DEBUG - error during build:
Info : DEBUG - RollupError: "default" is not exported by "resources/js/vendor/webauthn/webauthn.js", imported by "resources/js/data/webauthn/loginWebAuthn.ts".
Info : DEBUG -     at error (file:///var/www/lychee/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
Info : DEBUG -     at Module.error (file:///var/www/lychee/node_modules/rollup/dist/es/shared/node-entry.js:12781:16)
Info : DEBUG -     at Module.traceVariable (file:///var/www/lychee/node_modules/rollup/dist/es/shared/node-entry.js:13218:29)
Info : DEBUG -     at ModuleScope.findVariable (file:///var/www/lychee/node_modules/rollup/dist/es/shared/node-entry.js:11635:39)
Info : DEBUG -     at ReturnValueScope.findVariable (file:///var/www/lychee/node_modules/rollup/dist/es/shared/node-entry.js:5935:38)
Info : DEBUG -     at FunctionBodyScope.findVariable (file:///var/www/lychee/node_modules/rollup/dist/es/shared/node-entry.js:5935:38)
Info : DEBUG -     at ReturnValueScope.findVariable (file:///var/www/lychee/node_modules/rollup/dist/es/shared/node-entry.js:5935:38)
Info : DEBUG -     at FunctionBodyScope.findVariable (file:///var/www/lychee/node_modules/rollup/dist/es/shared/node-entry.js:5935:38)
Info : DEBUG -     at ChildScope.findVariable (file:///var/www/lychee/node_modules/rollup/dist/es/shared/node-entry.js:5935:38)
Info : DEBUG -     at FunctionScope.findVariable (file:///var/www/lychee/node_modules/rollup/dist/es/shared/node-entry.js:5935:38)
Info : DEBUG - + ynh_exit_properly
Attention : Upgrade failed ... attempting to restore the safety backup (Yunohost first need to remove the app for this) ...
```

**Comment by ericgaspar** [comment]
!testme

**Comment by OniriCorpe** [comment]
it worked!
[forgotten =1](https://github.com/YunoHost-Apps/lychee_ynh/pull/105/commits/651a19df8e7032cd7ad4b383d0b18f3262f4528a)

```text
Info : Updating sources...
Info : Updating system_user...
Info : Updating install_dir...
Info : Updating data_dir...
Info : Updating permissions...
Info : Updating apt...
Info : Updating database...
Info : [....................] > Ensuring downward compatibility...
Info : [+++.................] > Upgrading source files...
Info : [###++++.............] > Upgrading dependencies...
Info : [#######+............] > Upgrading PHP-FPM configuration...
Info : [########+...........] > Installing app with Composer...
Info : [#########+++++++....] > Installing lychee...
Info : [################+++.] > Building...
Info : [####################] > Upgrade of lychee completed
Succès ! lychee mis à jour
Succès ! Mise à jour terminée
```

**Pull request merged**
