### PR TITLE
Add admin user on install

### PR DESCRIPTION
**Pull request by DeMiro5001**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by DeMiro5001** [comment]
!testme

**Comment by orhtej2** [comment]
@DeMiro5001 do you want to maintain this app?

**Comment by DeMiro5001** [comment]
> @DeMiro5001 do you want to maintain this app?

Since I am using it, yes

**Comment by DeMiro5001** [comment]
@orhtej2 the ci test is successful but the validation leads to this error that isn't taken into account by the Ci : 

```
 > Validating that the app lychee can/can't be accessed with its URL...

URL     : https://sub.domain.tld/
Title   : Lychee v6
Content extract:
If you can read me, it means that you misconfigured Lychee.
Please check that:
```

The app is redirecting to domain.com/gallery when visiting the app url. So I think there is something to be done for tests.toml but I don't know what

**Comment by orhtej2** [comment]
I've checked on local install, this is NOT an error, but rather a placeholder content that's fetched then discarded.
Lychee fetches this page, and as a part of it fetches JS code that does the proper page rendering by interacting with Lychee's API.

**Pull request merged**
