### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by alexAubin**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by alexAubin** [comment]
!testme

**Review by alexAubin — COMMENTED** [review]
LGTM but I don't know if the Error 500 during upgrade from previous version is something to worry about :/

**Comment by ericgaspar** [comment]
!testme

**Comment by alexAubin** [comment]
Not sure why exactly, but now the app expects to find a php-fpm.conf:

```
208677 INFO [######+.............] > Configuring PHP-FPM...
[...]
211538 DEBUG - + '[' -e /var/cache/yunohost/app_tmp_work_dirs/app_1ezvgg3u/app_folder/conf/php-fpm.conf ']'
211538 DEBUG - + ynh_die '--message=Unable to find template to configure PHP-FPM.'
```

**Comment by ericgaspar** [comment]
!testme

**Comment by alexAubin** [comment]
zblerg i don't know watdo with this PR ? CI is level 6, upgrade failing from old versions because somehow there's a 500 error, but not clue why x_x

**Comment by tituspijean** [comment]
Error seems to be due to bad cache (they changed caching system last year). I managed to solve it by running `sudo -u lychee php8.0 artisan view:clear`

**Comment by tituspijean** [comment]
!gogogadgetotitus

**Pull request merged**
